### ISSUE TITLE
I F'ed up again :/

### ISSUE THREAD

**Issue by GalaxyLinus** [AriliusClient/Cornos#39]
Sorry for wasting your time, reply whenever you want
PS: I added some mods, didn't work, removed them, still didn't work

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/1/21 3:33 PM
Description: Initializing game

java.lang.IllegalStateException: Could not load icon: Corrupt PNG
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9)
	at net.minecraft.client.util.Window.setIcon(Window:170)
	at me.constantindev.ccl.Cornos.onMinecraftCreate(Cornos.java:38)
	at net.minecraft.client.MinecraftClient.handler$bid000$createClient(MinecraftClient:12381)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:592)
	at net.minecraft.client.main.Main.main(Main:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 405723384 bytes (386 MB) / 1482162176 bytes (1413 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 2
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3072m
	Suspected Mods: Cornos (ccl), Fabric Loader (fabricloader)
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.9
		advancednbttooltip: Advanced NBT Tooltips 1.4.0+build.3-1.16.5
		advancementinfo: AdvancementInfo 1.16.5-fabric0.30.0-1.2
		afkpeace: AFKPeace 4.6.0
		amecs: Amecs 1.3.3+mc.1.16.3
		amecsapi: Amecs API 1.1.3+mc1.16.5
		antiantixray: AntiAntiXray 1.0.0
		architectury: Architectury 1.9.136
		armorhotswap: ArmorHotswap 1.0
		autoclicker-fabric: Auto Clicker 1.0.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		baritone: Baritone 1.6.3
		blockmeter: Block Meter 1.2.0-fabric-1.16.3
		ccl: Cornos 1.0.0
		chat-up: Chat Up! 1.0
		clientcommands: Client Commands 2.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.15
		com_alibaba_fastjson: fastjson 1.2.56
		com_cedarsoftware_json-io: json-io 4.10.1
		com_googlecode_json-simple_json-simple: json-simple 1.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_oneandone_composite-jks: composite-jks 1.0
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		command-gui-buttons: Command GUI Buttons 1.0.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dynamicfps: Dynamic FPS 2.0.1
		easiervillagertrading: EasierVillagerTrading 1.16.4-fabric0.25.1-1.5.3
		eggtab: Egg Tab 2.1.0+1.16-fabric
		entityculling: EntityCulling-Fabric 1.1.1
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fishelp: Fishelp 1.0.2
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		grabcraft-downloader: GrabcraftLitematic 1.16.4-fabric0.25.1-0.4
		grass_kiss: Grass Kiss 1.16.2-fabric0.17.2-0.3.0
		held-item-info: Held Item Info 1.1.3
		horsestatsvanilla: Horse Stats Vanilla 4.1.4
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		inertia: Inertia Client 1.16.5
		inventoryprofiles: Inventory Profiles 0.4.2
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		krypton: Krypton 0.1.1
		lanserverproperties: Lan Server Properties ${version}
		libgui: LibGui 3.2.2+1.16.3
		lightoverlay: Light Overlay 5.8.0
		litematica: Litematica 0.0.0-dev.20201103.184101
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		lwat: LoginWithAccessToken 1.0.0
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.0.1
		modid: Litematica BRRRRRRRifier 1.0.0
		modmenu: Mod Menu 1.16.7
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		monster-in-the-closet: Monsters in the Closet 1.0.0
		more_tooltips: MoreTooltips 1.0.1
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		multiconnect: MultiConnect 1.3.35
		multiconnect-api: MultiConnect API 1.3.35
		nojumpscare: NoJumpscare 1.0.1+1.16
		nostrip: No Strip 1.2.0-1.16.2+
		notenoughcrashes: Not Enough Crashes 3.1.5
		opitems: Op Items 1.0.0
		petowner: Pet Owner 1.7.1-1.16.2+
		phosphor: Phosphor 0.7.1+build.11
		pickblockstate: Pick-BlockState 1.0.0
		pistorder: Pistorder 1.2.0
		pling: Pling 1.3.0
		rad: Reload Audio Driver 1.0.1
		rebind-narrator: Rebind Narrator 1.0.0
		roughlyenoughitems: Roughly Enough Items 5.11.188
		roughlyenoughitems-api: REI (API) 5.11.188
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.188
		roughlyenoughitems-runtime: REI (Runtime) 5.11.188
		sectionsign: SectionSign 1.0.2
		sheepconsistency: Sheep Consistency 1.0.2
		slimeblockredstone: Slime Block in Redstone Tab 2.1.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.1.0
		statssearch: StatsSearch 1.16.4-fabric0.25.1-1.0.1
		tellme: TellMe 0.9.2
		timetolive: Time To Live 0.2
		tooltipfix: ToolTip Fix 1.0.2-1.16
		tweed: Tweed API 3.0.0-beta.22
		ublowfire: Low Fire 1.0.1
		worldedit: WorldEdit 7.2.4+5723-e3bfc64
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) R5 Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.35.02 27.20.1034.6, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 2x AMD A9-9425 RADEON R5, 5 COMPUTE CORES 2C+3G 
```

**Comment by 0x150** [comment]
did you replace assets in the mod? seems as if mf couldnt load the process icon, which normally is just the "cc" image

**Comment by GalaxyLinus** [comment]
thanks I'm dumb

FloppaDev ***@***.***> schrieb am Do., 1. Apr. 2021, 18:00:

**Comment by 0x150** [comment]
alr
