### ISSUE TITLE
opening Inventory Crashes World

### ISSUE THREAD

**Issue by GalaxyLinus** [AriliusClient/Cornos#57]
´´´
---- Minecraft Crash Report ----
// Sorry :(

Time: 5/8/21 8:57 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: me/constantindev/ccl/gui/FunnyItemsScreen
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.init(InventoryScreen:52)
	at net.minecraft.client.gui.screen.Screen.init(Screen:325)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient:922)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1664)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1534)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.MinecraftClient.handler$bjd000$afterCrashHandled(MinecraftClient:11904)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:699)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: me.constantindev.ccl.gui.FunnyItemsScreen
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
Details:
	All players: 1 total; [class_746['GalaxyLinus'/60, l='ClientLevel', x=4577.97, y=80.03, z=-8874.82]]
	Chunk stats: SodiumChunkCache: 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (4581,71,-8883), Chunk: (at 5,4,13 in 286,-556; contains blocks 4576,0,-8896 to 4591,255,-8881), Region: (8,-18; contains chunks 256,-576 to 287,-545, blocks 4096,0,-9216 to 4607,255,-8705)
	Level time: 849769 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bjd000$onCrash(class_310.java:11912)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.class_310.handler$bjd000$afterCrashHandled(class_310.java:11904)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 857688568 bytes (817 MB) / 1881145344 bytes (1794 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 2
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3072m
	Suspected Mods: Fabric Loader (fabricloader)
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.9
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.12
		advancednbttooltip: Advanced NBT Tooltips 1.4.0+build.3-1.16.5
		advancementinfo: AdvancementInfo 1.16.5-fabric0.30.0-1.2
		afkpeace: AFKPeace 4.6.3
		amecs: Amecs 1.3.4+mc.1.16.3
		amecsapi: Amecs API 1.1.4+mc1.16.5
		antiantixray: AntiAntiXray 1.0.0
		architectury: Architectury 1.9.136
		autoclicker-fabric: Auto Clicker 1.0.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		baritone: Baritone 1.6.3
		bleachhack: BleachHack 1.16.5
		blockmeter: Block Meter 1.2.0-fabric-1.16.3
		ccl: Cornos 1.0.0
		chat-up: Chat Up! 1.0
		clientcommands: Client Commands 2.4.10
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.15
		com_alibaba_fastjson: fastjson 1.2.56
		com_cedarsoftware_json-io: json-io 4.10.1
		com_github_vatuu_discord-rpc: discord-rpc 1.6.2
		com_googlecode_json-simple_json-simple: json-simple 1.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		command-gui-buttons: Command GUI Buttons 1.1.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		disabler: Disabler 0.0.1
		dynamicfps: Dynamic FPS 2.0.1
		easiervillagertrading: EasierVillagerTrading 1.16.4-fabric0.25.1-1.5.3
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enhancedblockentities: Enhanced Block Entities 0.3.1
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.0+kotlin.1.5.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fishelp: Fishelp 1.0.2
		grass_kiss: Grass Kiss 1.16.2-fabric0.17.2-0.3.0
		held-item-info: Held Item Info 1.1.3
		horsestatsvanilla: Horse Stats Vanilla 4.1.4
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		indium: Indium 1.0.0
		inventoryprofiles: Inventory Profiles 0.4.2
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		krypton: Krypton 0.1.1
		lanserverproperties: Lan Server Properties ${version}
		libgui: LibGui 3.2.2+1.16.3
		lightoverlay: Light Overlay 5.8.0
		litematica: Litematica 0.0.0-dev.20210120.213004
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		lwat: LoginWithAccessToken 1.0.0
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		minecraft: Minecraft 1.16.4
		modid: Litematica BRRRRRRRifier 1.0.0
		modmenu: Mod Menu 1.16.7
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		monster-in-the-closet: Monsters in the Closet 1.0.0
		more_tooltips: MoreTooltips 1.0.1
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		multiconnect: MultiConnect 1.3.35
		multiconnect-api: MultiConnect API 1.3.35
		nicephore: Nicephore fabric-1.16.x-1.1.5
		nojumpscare: NoJumpscare 1.0.1+1.16
		nostrip: No Strip 1.2.0-1.16.2+
		notenoughcrashes: Not Enough Crashes 3.2.0
		opitems: Op Items 1.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.0
		petowner: Pet Owner 1.7.1-1.16.2+
		phosphor: Phosphor 0.7.1+build.11
		pickblockstate: Pick-BlockState 1.0.0
		pistorder: Pistorder 1.2.0
		pling: Pling 1.3.0
		quickreplant: quickreplant 1.0.0
		rad: Reload Audio Driver 1.0.1
		rebind-narrator: Rebind Narrator 1.0.0
		reeses-sodium-options: Reese's Sodium Options 1.0.0
		roughlyenoughitems: Roughly Enough Items 5.11.188
		roughlyenoughitems-api: REI (API) 5.11.188
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.188
		roughlyenoughitems-runtime: REI (Runtime) 5.11.188
		sectionsign: SectionSign 1.0.2
		sheepconsistency: Sheep Consistency 1.0.2
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		slimeblockredstone: Slime Block in Redstone Tab 2.1.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.1.1-SNAPSHOT
		statssearch: StatsSearch 1.16.4-fabric0.25.1-1.0.1
		stendhal: Stendhal 1.1.0
		tellme: TellMe 0.9.2
		timetolive: Time To Live 0.2
		tooltipfix: ToolTip Fix 1.0.2-1.16
		tweed: Tweed API 3.0.0-beta.22
		ublowfire: Low Fire 1.0.1
		worldedit: WorldEdit 7.2.4+5723-e3bfc64
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) R5 Graphics GL version 4.6.14830 Compatibility Profile Context 21.4.1 27.20.21002.112, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks.zip, file/redstonepack.zip, file/Customlang.zip, file/Better Enchantment Names (color-coded).zip
	Current Language: Deutsch (Deutschland)
	CPU: 2x AMD A9-9425 RADEON R5, 5 COMPUTE CORES 2C+3G 
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
´´´

**Comment by 0x150** [comment]
try reinstalling the client, the funny items screen wasnt in the class. nothing i can do about it, you gotta remove the mod and add it back
